### ISSUE TITLE
Issues on Page "Using Marlowe Runtime"

### ISSUE THREAD

**Issue by jhbertra** [input-output-hk/marlowe-doc#72]
- Page is currently a stub
- Marlowe chain sync / chain seek protocol are not part of the runtime's public interface, so this page should not mention them.
  - Coverage of this could be done in a separate page "runtime internals"
- It might be better to rework this page to be a high-level overview of the different interfaces available, with links to their respective pages:
  - Marlowe runtime CLI
  - Runtime protocol
  - Web server

**Comment by joseph-fajen** [comment]
Comments have been addressed.
