### ISSUE TITLE
Issues on page "Runtime Executables for Backend Services"

### ISSUE THREAD

**Issue by jhbertra** [input-output-hk/marlowe-doc#73]
- Page doesn't need to describe what a "backend service" is
- Lots of missing / outdated content
- I think a "Runtime Internals" index page with sub-pages may be more useful. Here are the sub-pages which we should cover:
  - `marlowe-chain-indexer` service
  - `marlowe-chain-sync` service
  - `marlowe-indexer` service
  - `marlowe-sync` service
  - `marlowe-tx` service
  - `marlowe-proxy` service

**Comment by joseph-fajen** [comment]
Comments have been addressed.
