### ISSUE TITLE
Issues on page `Marlowe Runtime CLI`

### ISSUE THREAD

**Issue by jhbertra** [input-output-hk/marlowe-doc#74]
- Accuracy: `Heavyweight: Only works if all of the Marlowe Runtime services are installed and running.`
  - This isn't accurate - the CLI is able to connect to a runtime running on a separate host machine. It just needs a host name and port number to connect.
- Page is a stub
- Missing a link for `show the history of a contract` (via `marlowe log` command)

**Comment by joseph-fajen** [comment]
Comments have been addressed.
